
/****************************************************************************
;---------------------------------------
;  CMT2310A Configuration File
;  Generated by CMOSTEK RFPDK 1.53_Update4
;  2024.06.20 16:37
;---------------------------------------
; Mode                       = Advanced
; Part Number                = CMT2310A
; Frequency                  = 434.650 MHz
; DC-DC                      = On
; Demodulation               = GFSK
; Xtal Cap Load              = 2
; Data Rate                  = 1.800 kbps
; Deviation                  = 3.000 kHz
; Tx Xtal Tol.               = 10 ppm
; Rx Xtal Tol.               = 10 ppm
; TRx Matching Network Type  = 20 dBm
; Tx Power                   = +20 dBm
; Gaussian BT                = 0.5
; PA Ramp                    = On-Autosel Rampstep
; PA Ramp Step               = NA
; RF Performance             = NA
; Output Drive Capability    = 0.5mA
; Rx Duty-Cycle              = On
; Tx Duty-Cycle              = Off
; Sleep Timer                = On
; Sleep Time                 = 24.00000 ms
; Rx Timer                   = On
; Rx Time T1                 = 8.00 ms
; Rx Time T2                 = 70.00 ms
; Rx Exit State              = SLEEP
; Tx Exit State              = SLEEP
; TX Duty Cycle Persist      = Off
; Packet Done Exit           = Off
; TX Duty-Cycle Times        = 0
; SLP Mode                   = Mode 7
; RSSI Valid Source          = RSSI Compare
; PJD Window                 = NA
; RSSI Compare TH            = -107 dBm
; CDR Type                   = Counting
; AFC                        = enable
; FSK2 Data Map              = 0:F-low 1:F-high
; FSK4 Data Map              = NA
; FSK4 RX Data Map           = NA
; CDR Type                   = Counting
; CDR Range Sel FSK          = NA
; Channel BW                 = autosel
; Baseband BW FSK            = autosel
; Data Mode                  = Direct
; Packet Mode                = Normal
; PiggyBacking               = Disable
; Manchester                 = Disable
; Manchester Type            = NA
; Whitening                  = Disable
; Whiten Type                = NA
; Whiten Seed Type           = NA
; Whiten Seed                = NA
; FEC                        = Disable
; FEC Type                   = NA
; FEC Padding Code           = NA
; crc err clear fifo         = Not Clear
; Tx Packet Gap              = 32 symbol(s)
; Tx Packet Number           = 1 packet(s)
; Tx Prefix Type             = 0
; Packet Type                = Variable Length
; Address-Length Position    = First Address,then Length
; Length Size                = 2-byte
; Payload Bit Order          = Start from msb
; Address Field              = Disable
; Preamble Rx Size           = 1
; Preamble Tx Size           = 8
; Preamble Value             = 170
; Preamble Unit              = 8-bit
; Sync Size                  = 3-byte
; Sync Format                = S2LP
; Sync Value                 = 3003605
; Sync Manchester            = Disable
; Sync Value Selection       = Sync Value
; Sync FEC Value             = 3003605
; Sync Tolerance             = None
; Address Detect Mode        = None
; Address Split Mode         = NA
; Address Size               = NA
; Address Err Mask           = NA
; Address Free               = NA
; Dest Addr Value            = NA
; Src Addr Value             = NA
; Dest Addr Bit Mask         = NA
; Src Addr Bit Mask          = NA
; Sequence Num               = None
; Sequence Num Match         = off
; Sequence Num Mode          = NA
; Sequence Num Value         = NA
; FCS2                       = None
; FCS2 Value                 = NA
; Payload Length             = 32
; CRC Options                = None
; CRC Swap                   = NA
; CRC Seed                   = NA
; CRC Bit Invert             = NA
; CRC Range                  = NA
; CRC Polynomial             = NA
; CRC Bit Order              = NA
; CRC Refin                  = NA
; CRC_Refout                 = NA
; Frequency Hopping Mode     = Mode 2
; Freq Hopping Space         = 10 kHz
; Hopping Channels           = 10
; CSMA Mode                  = Disable
; CSMA RSSI Detection        = NA
; Hopping Persist            = Disable
; Hopping Intermediate State = TRFS
; CSMA Sleep Timer Random    = NA
; CSMA Rx Time               = NA
; CSMA Sleep Time M          = NA
; CSMA Sleep Time R          = NA
; CSMA Persist               = NA
; CSMA Detect Times          = NA
; Tx Auto Hopping            = Disable
; Rx Auto Hopping            = Disable
; Auto Acknowledge           = off
; Auto Resend                = off
; Maximum Resend Times       = 1
; RSSI Detect Mode           = always
; LFOSC LFXO Sel             = LFOSC(32kHz)
; LF Clock Out               = off
; Dout Mute                  = disable
; Dout Mute Sel              = NA
; dout adjust mode           = disable
; Dout Adjust Percentage     = NA
; LBD Threshold              = 2.4 v
; Antenna Diversity          = off
; Antenna Switch Mode        = NA
; Collision Detect           = off
; Collision Step             = NA
; RSSI Offset dB             = NA
; RSSI Offset Sel            = autosel

;---------------------------------------
;  The following are the Register contents
;---------------------------------------

*****************************************************************************/

#define __CMT2310A_GFSK_434650kHz_1800pbs_3kHz_20dBm_10ppm_MODE7_CDRCNT_C

#include "main.h"
#include "CMT2310A_reg.h"
#include "CMT2310A_def.h"


/* [CMT page0] */
const uint8_t g_cmt2310a_434_mode7_cdrcnt_rssi124_page0[CMT2310A_PAGE0_SIZE] = {
    0x08,
    0x08,
    0x00,
    0xAA,
    0x04,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0xD5,
    0xD4,
    0x2D,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0xD5,
    0xD4,
    0x2D,
    0x1F,
    0x00,
    0x21,
    0x00,
    0x00,
    0x00,
    0x00,
    0x2D,
    0x00,
    0x00,
    0x00,
    0x2D,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x45,
    0x1F,
    0x00,
    0x00,
    0x00,
    0x00,
    0x08,
    0x00,
    0x00,
    0x00,
    0x00,
    0x1F,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0xE4,
    0x10,
    0x19,
    0x27,
    0x80,
    0x20,
    0x20,
    0x60,
    0xD6,
    0xC2,
    0x38,
    0x04,
    0xD0,
    0xE0,
    0x80,
    0x00,
    0x41,
    0x00,
    0x01,
    0x00,
    0x02,
    0x00,
    0x00,
    0x03,
    0x04,
};   

/* [CMT page1] */
const uint8_t g_cmt2310a_434_mode7_cdrcnt_rssi124_page1[CMT2310A_PAGE1_SIZE] = {
    0x10,
    0x16,
    0x00,
    0xFF,
    0x00,
    0xCD,
    0x02,
    0x28,
    0x50,
    0x87,
    0x31,
    0x5B,
    0x08,
    0x38,
    0xFF,
    0x00,
    0x6C,
    0x99,
    0x99,
    0x0A,
    0xB4,
    0xB0,
    0x03,
    0x60,
    0x20,
    0x08,
    0x06,
    0x18,
    0x04,
    0x00,
    0xA0,
    0x7F,
    0x00,
    0x18,
    0x00,
    0x00,
    0x1F,
    0xE4,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0xCA,
    0x6C,
    0x99,
    0x19,
    0xDB,
    0x6B,
    0x00,
    0x80,
    0x0F,
    0x64,
    0x06,
    0x02,
    0xB0,
    0x03,
    0x00,
    0x36,
    0x01,
    0x20,
    0xC8,
    0x63,
    0xA1,
    0x72,
    0x45,
    0x58,
    0x40,
    0x42,
    0x74,
    0xF0,
    0x0F,
    0x01,
    0x17,
    0xE6,
    0x54,
    0x08,
    0x39,
    0xE2,
    0x19,
    0x14,
    0x01,
    0xB4,
    0x06,
    0x0F,
    0x09,
    0x4C,
    0x00,
    0x00,
    0xF6,
    0x00,
    0x00,
    0x00,
    0x10,
    0x95,
    0x00,
    0x00,
    0x47,
    0x12,
    0x25,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
};   

//#define CMT2310A_AUTO_HOP_ENABLE
#ifdef  CMT2310A_AUTO_HOP_ENABLE
#define freq_space_val           0x0A
#define freq_times_val           0x0A
#define freq_switch_state_val    0x01
#define freq_hop_persist_val     0x00

/* [CMT page2] */
const uint8_t g_cmt2310a_434_mode7_cdrcnt_rssi124_page2[CMT2310A_PAGE2_SIZE] = {
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
     0x00,
};   
#endif 
 
